version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123
  server:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
    - "8888:8080"
  data_loader:
    build:
      dockerfile: Dockerfile
      context: ./data_loader
    depends_on:
      - db
