version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  server:
    build:
      dockerfile: Dockerfile.server
      context: .
    ports:
    - "8888:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  loader:
    build:
      dockerfile: Dockerfile.loader
      context: ./data_loader
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  ngrok:
    image: shkoliar/ngrok
    ports:
      - 4551:4551
    links:
      - server
    environment:
      - DOMAIN=server
      - PORT=8080

