version: "3"
services:
  db:
    build:
      dockerfile: Dockerfile.postgres
      context: .
  server:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
    - "8888:8080"
    depends_on:
      - db
  data_loader:
    build:
      dockerfile: Dockerfile
      context: ./data_loader
    depends_on:
      - db
